### ISSUE TITLE
Opinion, add option use own artwork

### ISSUE THREAD

**Issue by RFSVIEIRA** [RobG66/Gamelist-Manager#10]
In the scraper page, add option to add paths for already exist artwork, will be good for how has some addons and want to migrate to batocera/retrobat. So it will create the gamelist with all meta+paths to already artwork in folders structure.. so user add paths for marquee, video, fanart, etc.. and add option off user define new tags more 1 our 2. It scan the room folder creates the gamelist with own artwork , adds meta info, then user can manage new changes , Thanks

**Comment by RobG66** [comment]
This is a work in progress feature I am close to finishing.  It will be available by the Tools menu with the ability to:
- Add existing artwork to the gamelist based upon exact matches.
- Search for missing/unused media and corrupt/single color images.  You can then backup, delete, clear references
- Search for new media in another folder, like a downloaded media pack.  The program uses fuzzy logic to try and make matches.  Fuzzy matches are tricky, but are already used with Emumovies scraping.

**Comment by RFSVIEIRA** [comment]
Great, I was talking about it, BCS actually I use a program to create the gamelist based in rom folder and doesn't have all the tags with paths options, bcs that I talk here option of add 1 our 3 tags user define tag and path..  doesn't have option of images extensions, and add more than one ROM extension type, then I update the metadata info with retrobat scraper disabling media, it just update and add meta info. Your program looks great so I give a shoot with this idea this new options will make it perfect creating a gamelist base ROM folders and paths for the already exist artwork(sufix. Ex gameName-marquee Can be and option to). Your code is to advanced for I thoutch I'm just a auto curiose read and do some little thinks Thanks

**Comment by RobG66** [comment]
This is getting close.  In a week or so I hope to finally release something for easily adding additional artwork.  It won't have drag and drop, but I do plan to look at that after this.

**Comment by RFSVIEIRA** [comment]
Thanks, I already did a small simple c# gamelist creator/converter(still in command )from RetroFe systems to RetroBat. But it only adds the tags (name, desc, fanart, image, bezel, etc.. )and folder tags to, with the path. For gameInfo I need scrap with RetroBat... So it's 2 steps losing lots of time. I think your programm is Great. But if doesn't fit for converting RetroFe, Wen I done the GUI I can share to community.

**Comment by RobG66** [comment]
There's an oversight I made when loading gamelists which is fixed in the next version.  Some other utilities add additional metadata elements which changes the table order when the xml is loaded into a dataset.  I don't know if that's actually serving a purpose or just self promotion of the tool (or both).  I never add anything extra and if there's something that's not standard which my tool doesn't know about, it's left alone and will still be there when you save.  

 Can you share a retroFe gamelist?  I'd like to see what the format looks like.  I have never used that before.  Is it a derivative of ES?

**Comment by RFSVIEIRA** [comment]
I send to your discord, is easy there.

**Comment by RobG66** [comment]
Closing issue

**Comment by jpdonald** [comment]
Version 7.4.. Admirable work. Everything works perfectly.
But no more drag and drop for media.
So I'm going back to your old version 5.3 which allows it.
(this is the only version that works correctly for me)
In addition to media, a click and drop for manuals (PDF) would also be welcome.
I use Batocera. Thank you for this very practical GamelistManager.
