### ISSUE TITLE
Ability to edit game description

### ISSUE THREAD

**Issue by 20GotoTen** [RobG66/Gamelist-Manager#6]
Hi! I'm enjoying using your app. It would be great if you could manually edit the game description in addition to the other currently editable fields. Looking forward to seeing what else you may add in the future! Thank you.

**Comment by RobG66** [comment]
Sure, no problem.  I thought I already had that in there.  I'll post a new version soon.

**Comment by RobG66** [comment]
Version 4.9 now has this.  Enjoy!
