### ISSUE TITLE
Unhandled exception when checking for media

### ISSUE THREAD

**Issue by rafma0** [RobG66/Gamelist-Manager#7]
Hi, thank you for this tool.

I'm using it mainly to check for missing media, and I think I found a small bug.

If you don't have an `images` or `videos` folder in your gamelist path, it will return a `Unhandled exception` with a `Could not find a part of the path` error.

I have all my media in custom relative paths like:
```
<image>./boxart/game.png</image>
<video>./snaps/game.mp4</video>
```

The tool can check for these paths just fine if I create empty folders for images and videos.

**Comment by RobG66** [comment]
Thanks for the report.  I will get it fixed up in the next update!  :)

**Comment by RobG66** [comment]
I've added checks for folders now.  Version 6 inbound.....
